### ISSUE TITLE
StringIndexOutOfBoundException from lusearch using GenCopy

### ISSUE THREAD

**Issue by wks** [mmtk/mmtk-openjdk#100]
Clone the following repositories or add them as remote
```
cd /path/to/mmtk-core
git remote add wks-github git@github.com:wks/mmtk-core.git
git fetch
git checkout wks-github/fix-safepoint-sync

cd /path/to/mmtk-openjdk
git remote add wks-github git@github.com:wks/mmtk-openjdk.git
git fetch
git checkout wks-github/fix-safepoint-sync

cd /path/to/mmtk-openjdk/repos/openjdk
git remote add wks-github git@github.com:wks/openjdk.git
git fetch
git checkout wks-github/fix-safepoint-sync
```

Compile openjdk as usual, and execute it using the following command:

```sh
env RUST_BACKTRACE=1 MMTK_MIN_NURSERY=1048576 MMTK_MAX_NURSERY=1048576 MMTK_PLAN=GenCopy RUST_LOG=warn /path/to/mmtk-openjdk/repos/openjdk/build/linux-x86_64-normal-server-slowdebug/jdk/bin/java -XX:+UseThirdPartyHeap -Xms512M -Xmx512M -Xlog:vmthread=warning:stdout -Xlog:safepoint=warning:stdout -Xlog:gc=warning:stdout -Xlog:thread=debug:stdout -jar ./dacapo-9.12-MR1-bach.jar lusearch
```

I suppressed most logging I added for debugging issue https://github.com/mmtk/mmtk-openjdk/issues/93.

Then there is a very high chance to see a `StringIndexOutOfBoundException`:

```
java.lang.StringIndexOutOfBoundsException: offset 0, count 8, length 0
        at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
        at java.base/java.lang.String.rangeCheck(String.java:280)
        at java.base/java.lang.String.<init>(String.java:276)
        at org.apache.lucene.analysis.Token.term(Token.java:363)
        at org.apache.lucene.queryParser.QueryParser.getFieldQuery(QueryParser.java:550)
        at org.apache.lucene.queryParser.QueryParser.Term(QueryParser.java:1331)
        at org.apache.lucene.queryParser.QueryParser.Clause(QueryParser.java:1218)
        at org.apache.lucene.queryParser.QueryParser.Query(QueryParser.java:1146)
        at org.apache.lucene.queryParser.QueryParser.TopLevelQuery(QueryParser.java:1135)
        at org.apache.lucene.queryParser.QueryParser.parse(QueryParser.java:170)
        at org.dacapo.lusearch.Search$QueryProcessor.run(Search.java:237)
        at org.dacapo.lusearch.Search$QueryThread.run(Search.java:179)
java.lang.NullPointerException
        at org.apache.lucene.search.Searcher.createWeight(Searcher.java:185)
        at org.apache.lucene.search.Searcher.search(Searcher.java:136)
        at org.dacapo.lusearch.Search$QueryProcessor.run(Search.java:241)
        at org.dacapo.lusearch.Search$QueryThread.run(Search.java:179)
```

Increasing the nursery size by replacing `MMTK_MIN_NURSERY=1048576 MMTK_MAX_NURSERY=1048576` with `MMTK_MIN_NURSERY=2097152 MMTK_MAX_NURSERY=2097152`, and the exception seems to go away.

**Comment by wks** [comment]
Setting the `MMTK_ENABLE_ALLOCATION_FASTPATH` macro in `mmtkBarrierSet.hpp` to `false` will increase the likelihood for such an exception to thrown.

It also causes the VM to crash for two other reasons.

Stack trace 1 (a GC worker thread):

```
thread '<unnamed>' panicked at '0x160000000000 of size 4096 is not mapped', /home/wks/projects/mmtk-github/mmtk-core/src/util/memory.rs:121:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/std/src/panicking.rs:460:5
   2: mmtk::util::memory::panic_if_unmapped
             at /home/wks/projects/mmtk-github/mmtk-core/src/util/memory.rs:121:18
   3: mmtk::util::metadata::side_metadata::global::ensure_metadata_is_mapped
             at /home/wks/projects/mmtk-github/mmtk-core/src/util/metadata/side_metadata/global.rs:314:5
   4: mmtk::util::metadata::side_metadata::global::load_atomic
             at /home/wks/projects/mmtk-github/mmtk-core/src/util/metadata/side_metadata/global.rs:324:9
   5: mmtk::policy::mallocspace::metadata::is_alloced_object
             at /home/wks/projects/mmtk-github/mmtk-core/src/policy/mallocspace/metadata.rs:156:5
   6: mmtk::policy::mallocspace::metadata::is_alloced
             at /home/wks/projects/mmtk-github/mmtk-core/src/policy/mallocspace/metadata.rs:152:5
   7: mmtk::policy::mallocspace::metadata::is_alloced_by_malloc
             at /home/wks/projects/mmtk-github/mmtk-core/src/policy/mallocspace/metadata.rs:148:50
   8: mmtk::policy::space::SFTMap::is_in_space
             at /home/wks/projects/mmtk-github/mmtk-core/src/policy/space.rs:245:13
   9: mmtk::util::address::ObjectReference::is_mapped
             at /home/wks/projects/mmtk-github/mmtk-core/src/util/address.rs:503:9
  10: mmtk::memory_manager::is_mapped_object
             at /home/wks/projects/mmtk-github/mmtk-core/src/memory_manager.rs:270:5
  11: is_mapped_object
             at /home/wks/projects/mmtk-github/mmtk-openjdk/mmtk/src/api.rs:159:5
  12: _ZNK8MMTkHeap5is_inEPKv
  13: _ZN2os14print_locationEP12outputStreamlb
  14: _ZN2os19print_register_infoEP12outputStreamPKv
  15: _ZN7VMError6reportEP12outputStreamb
  16: _ZN7VMError14report_and_dieEiPKcS1_P13__va_list_tagP6ThreadPhPvS7_S1_im
  17: _ZN7VMError14report_and_dieEP6ThreadjPhPvS3_PKcz
  18: _ZN7VMError14report_and_dieEP6ThreadjPhPvS3_
  19: JVM_handle_linux_signal
  20: _ZL13signalHandleriP9siginfo_tPv
  21: <unknown>
  22: _ZNK5Klass13layout_helperEv
  23: _ZN7oopDesc16size_given_klassEP5Klass
  24: _ZN7oopDesc4sizeEv
  25: _ZL20mmtk_get_object_sizePv
  26: <mmtk_openjdk::object_model::VMObjectModel as mmtk::vm::object_model::ObjectModel<mmtk_openjdk::OpenJDK>>::copy
             at /home/wks/projects/mmtk-github/mmtk-openjdk/mmtk/src/object_model.rs:92:30
  27: mmtk::util::object_forwarding::forward_object
             at /home/wks/projects/mmtk-github/mmtk-core/src/util/object_forwarding.rs:95:22
  28: mmtk::policy::copyspace::CopySpace<VM>::trace_object
             at /home/wks/projects/mmtk-github/mmtk-core/src/policy/copyspace.rs:179:17
  29: <mmtk::plan::gencopy::gc_work::GenCopyNurseryProcessEdges<VM> as mmtk::scheduler::gc_work::ProcessEdgesWork>::trace_object
             at /home/wks/projects/mmtk-github/mmtk-core/src/plan/gencopy/gc_work.rs:106:20
  30: <mmtk::plan::gencopy::gc_work::GenCopyNurseryProcessEdges<VM> as mmtk::scheduler::gc_work::ProcessEdgesWork>::process_edge
             at /home/wks/projects/mmtk-github/mmtk-core/src/plan/gencopy/gc_work.rs:132:26
  31: mmtk::scheduler::gc_work::ProcessEdgesWork::process_edges
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/gc_work.rs:455:13
  32: mmtk::scheduler::gc_work::<impl mmtk::scheduler::work::GCWork<<E as mmtk::scheduler::gc_work::ProcessEdgesWork>::VM> for E>::do_work
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/gc_work.rs:465:9
  33: <W as mmtk::scheduler::work::Work<mmtk::mmtk::MMTK<VM>>>::do_work
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/work.rs:34:9
  34: mmtk::scheduler::work::Work::do_work_with_stat
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/work.rs:14:9
  35: mmtk::scheduler::worker::Worker<C>::run
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/worker.rs:147:17
  36: mmtk::memory_manager::start_worker
             at /home/wks/projects/mmtk-github/mmtk-core/src/memory_manager.rs:178:5
  37: start_worker
             at /home/wks/projects/mmtk-github/mmtk-openjdk/mmtk/src/api.rs:123:5
  38: _ZN19MMTkCollectorThread3runEv
  39: _ZN6Thread8call_runEv
  40: _ZL19thread_native_entryP6Thread
  41: start_thread
  42: __GI___clone
```

Stack trace 2 (This is a Java thread) (Note that this is collected in a **different** execution):

```
Current thread (0x00007fb75c894000):  JavaThread "Query0" [_thread_in_Java, id=94744, stack(0x00007fb722be0000,0x00007fb722ce1000)]    
                                                                                     
Stack: [0x00007fb722be0000,0x00007fb722ce1000],  sp=0x00007fb722cdc310,  free space=1008k    
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)    
V  [libjvm.so+0x134e629]  VMError::report_and_die(int, char const*, char const*, __va_list_tag*, Thread*, unsigned char*, void*, void*, char const*, int, unsigned long)+0x81d    
V  [libjvm.so+0x134dda9]  VMError::report_and_die(Thread*, void*, char const*, int, char const*, char const*, __va_list_tag*)+0x57    
V  [libjvm.so+0x90b15e]  report_vm_error(char const*, int, char const*, char const*, ...)+0x146    
V  [libjvm.so+0xb56564]  HandleArea::allocate_handle(oopDesc*)+0x16c                 
V  [libjvm.so+0x563070]  Handle::Handle(Thread*, oopDesc*)+0xb2                      
V  [libjvm.so+0x11fea71]  StackValue::create_stack_value(frame const*, RegisterMap const*, ScopeValue*)+0x395    
V  [libjvm.so+0x133711e]  compiledVFrame::create_stack_value(ScopeValue*) const+0x36    
V  [libjvm.so+0x133702e]  compiledVFrame::expressions() const+0xf0                   
V  [libjvm.so+0x133407d]  vframeArrayElement::fill_in(compiledVFrame*, bool)+0x66b    
V  [libjvm.so+0x1335a6b]  vframeArray::fill_in(JavaThread*, int, GrowableArray<compiledVFrame*>*, RegisterMap const*, bool)+0x73    
V  [libjvm.so+0x13359ed]  vframeArray::allocate(JavaThread*, int, GrowableArray<compiledVFrame*>*, RegisterMap*, frame, frame, frame, bool)+0x169    
V  [libjvm.so+0x929654]  Deoptimization::create_vframeArray(JavaThread*, frame, RegisterMap*, GrowableArray<compiledVFrame*>*, bool)+0x38a    
V  [libjvm.so+0x9257b4]  Deoptimization::fetch_unroll_info_helper(JavaThread*, int)+0xe48    
V  [libjvm.so+0x92cb49]  Deoptimization::uncommon_trap(JavaThread*, int, int)+0x77    
                                                                                 
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)                   
v  blob 0x00007fb749030041                                                       
J 1441 c2 org.apache.lucene.queryParser.QueryParser.getFieldQuery(Ljava/lang/String;Ljava/lang/String;)Lorg/apache/lucene/search/Query; (626 bytes) @ 0x00007fb750c7f68c [0x00007fb750c7de00+0x000000000000188c]
J 1274 c2 org.apache.lucene.queryParser.QueryParser.Term(Ljava/lang/String;)Lorg/apache/lucene/search/Query; (1686 bytes) @ 0x00007fb750c1ae48 [0x00007fb750c1a920+0x0000000000000528]
J 1213 c2 org.apache.lucene.queryParser.QueryParser.Clause(Ljava/lang/String;)Lorg/apache/lucene/search/Query; (375 bytes) @ 0x00007fb750c09dbc [0x00007fb750c09620+0x000000000000079c]
J 1279 c2 org.apache.lucene.queryParser.QueryParser.Query(Ljava/lang/String;)Lorg/apache/lucene/search/Query; (215 bytes) @ 0x00007fb750bcf20c [0x00007fb750bcf080+0x000000000000018c]
J 1277 c2 org.apache.lucene.queryParser.QueryParser.parse(Ljava/lang/String;)Lorg/apache/lucene/search/Query; (155 bytes) @ 0x00007fb750c1709c [0x00007fb750c16d00+0x000000000000039c]
J 1397 c1 org.dacapo.lusearch.Search$QueryProcessor.run()V (205 bytes) @ 0x00007fb7497cd2b4 [0x00007fb7497cc440+0x0000000000000e74]
j  org.dacapo.lusearch.Search$QueryThread.run()V+92                              
v  ~StubRoutines::call_stub                                                      
```
```

**Comment by wks** [comment]
One more assertion failure:
```
thread '<unnamed>' panicked at 'assertion failed: self.gencopy().tospace().in_space(object)', /home/wks/projects/mmtk-github/mmtk-core/src/plan/gencopy/gc_work.rs:125:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/core/src/panicking.rs:93:14
   2: core::panicking::panic
             at /rustc/ae90dcf0207c57c3034f00b07048d63f8b2363c8/library/core/src/panicking.rs:50:5
   3: <mmtk::plan::gencopy::gc_work::GenCopyNurseryProcessEdges<VM> as mmtk::scheduler::gc_work::ProcessEdgesWork>::trace_object
             at /home/wks/projects/mmtk-github/mmtk-core/src/plan/gencopy/gc_work.rs:125:9
   4: <mmtk::plan::gencopy::gc_work::GenCopyNurseryProcessEdges<VM> as mmtk::scheduler::gc_work::ProcessEdgesWork>::process_edge
             at /home/wks/projects/mmtk-github/mmtk-core/src/plan/gencopy/gc_work.rs:132:26
   5: mmtk::scheduler::gc_work::ProcessEdgesWork::process_edges
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/gc_work.rs:455:13
   6: mmtk::scheduler::gc_work::<impl mmtk::scheduler::work::GCWork<<E as mmtk::scheduler::gc_work::ProcessEdgesWork>::VM> for E>::do_work
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/gc_work.rs:465:9
   7: mmtk::scheduler::work::GCWork::do_work_with_stat
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/work.rs:20:9
   8: mmtk::scheduler::worker::GCWorker<VM>::run
             at /home/wks/projects/mmtk-github/mmtk-core/src/scheduler/worker.rs:154:17
   9: mmtk::memory_manager::start_worker
             at /home/wks/projects/mmtk-github/mmtk-core/src/memory_manager.rs:177:5
  10: start_worker
             at /home/wks/projects/mmtk-github/mmtk-openjdk/mmtk/src/api.rs:123:5
  11: _ZN19MMTkCollectorThread3runEv
  12: _ZN6Thread8call_runEv
  13: _ZL19thread_native_entryP6Thread
  14: start_thread
  15: __GI___clone
```

**Comment by wks** [comment]
Reduce the nursery size to 512KB and the following stack trace will be easy to reproduce:

```
java.lang.NullPointerException
        at org.apache.lucene.search.Searcher.createWeight(Searcher.java:185)
        at org.apache.lucene.search.Searcher.search(Searcher.java:136)
        at org.dacapo.lusearch.Search$QueryProcessor.run(Search.java:241)
        at org.dacapo.lusearch.Search$QueryThread.run(Search.java:179)
```
