### ISSUE TITLE
DacapoChopin zxing failed

### ISSUE THREAD

**Issue by xinyu-zheng** [mmtk/mmtk-openjdk#104]
binding: 648bb27f4bb5c84a83f74fda1d699514548cf663
mmtk-core: d2324cff01438e8c2911c00e1c3c2e691b90471b

After running
```
MMTK_THREADS=1 MMTK_PLAN=SemiSpace /home/xinyuz/mmtk/mmtk-openjdk/repos/openjdk/build-with-sync-d2324cf-648bb27/linux-x86_64-normal-server-release/jdk/bin/java -XX:MetaspaceSize=500M -XX:+DisableExplicitGC -server -XX:-TieredCompilation -Xcomp -XX:+UseThirdPartyHeap -Djava.library.path=/home/xinyuz/probes -Dprobes=RustMMTk -Xms576M -Xmx576M -cp /usr/share/benchmarks/dacapo/dacapo-evaluation-git-69a704e.jar:/home/xinyuz/probes:/home/xinyuz/probes/probes.jar Harness -c probe.DacapoChopinCallback -n 5 zxing
```
I got
```
--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 24 processors detected, 24 threads used to drive the workload, in a possible range of [1,unlimited]
===== DaCapo evaluation-git-69a704e zxing starting warmup 1 =====
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dacapo.harness.Zxing.iterate(Zxing.java:44)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:216)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Harness.main(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:96)
	... 13 more
Caused by: java.lang.IllegalArgumentException
	at com.google.zxing.common.BitArray.isRange(BitArray.java:193)
	at com.google.zxing.oned.UPCEANReader.findStartGuardPattern(UPCEANReader.java:122)
	at com.google.zxing.oned.MultiFormatUPCEANReader.decodeRow(MultiFormatUPCEANReader.java:76)
	at com.google.zxing.oned.MultiFormatOneDReader.decodeRow(MultiFormatOneDReader.java:98)
	at com.google.zxing.oned.OneDReader.doDecode(OneDReader.java:155)
	at com.google.zxing.oned.OneDReader.decode(OneDReader.java:59)
	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
	at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:71)
	at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:148)
	at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:76)
	at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Digest validation failed for stdout.log, expecting 0x5ba0fbb5c278f7344ad9c9d153a323f6b6eda10c found 0xda39a3ee5e6b4b0d3255bfef95601890afd80709
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0x3c11277a27db939d6885f6da70bfcf741bd4414d
===== DaCapo evaluation-git-69a704e zxing FAILED warmup =====
===== DaCapo evaluation-git-69a704e zxing starting warmup 2 =====
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dacapo.harness.Zxing.iterate(Zxing.java:44)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:216)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Harness.main(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:96)
	... 13 more
Caused by: java.lang.IllegalArgumentException
	at com.google.zxing.common.BitArray.isRange(BitArray.java:193)
	at com.google.zxing.oned.UPCEANReader.findStartGuardPattern(UPCEANReader.java:122)
	at com.google.zxing.oned.MultiFormatUPCEANReader.decodeRow(MultiFormatUPCEANReader.java:76)
	at com.google.zxing.oned.MultiFormatOneDReader.decodeRow(MultiFormatOneDReader.java:98)
	at com.google.zxing.oned.OneDReader.doDecode(OneDReader.java:155)
	at com.google.zxing.oned.OneDReader.decode(OneDReader.java:59)
	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
	at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:71)
	at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:148)
	at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:76)
	at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Digest validation failed for stdout.log, expecting 0x5ba0fbb5c278f7344ad9c9d153a323f6b6eda10c found 0xda39a3ee5e6b4b0d3255bfef95601890afd80709
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0x3c11277a27db939d6885f6da70bfcf741bd4414d
===== DaCapo evaluation-git-69a704e zxing FAILED warmup =====
===== DaCapo evaluation-git-69a704e zxing starting warmup 3 =====
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.dacapo.harness.Zxing.iterate(Zxing.java:44)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:216)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at Harness.main(Unknown Source)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:96)
	... 13 more
Caused by: java.lang.IllegalArgumentException
	at com.google.zxing.common.BitArray.isRange(BitArray.java:193)
	at com.google.zxing.oned.UPCEANReader.findStartGuardPattern(UPCEANReader.java:122)
	at com.google.zxing.oned.MultiFormatUPCEANReader.decodeRow(MultiFormatUPCEANReader.java:76)
	at com.google.zxing.oned.MultiFormatOneDReader.decodeRow(MultiFormatOneDReader.java:98)
	at com.google.zxing.oned.OneDReader.doDecode(OneDReader.java:155)
	at com.google.zxing.oned.OneDReader.decode(OneDReader.java:59)
	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
	at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:71)
	at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:148)
	at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:76)
	at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:56)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Digest validation failed for stdout.log, expecting 0x5ba0fbb5c278f7344ad9c9d153a323f6b6eda10c found 0xda39a3ee5e6b4b0d3255bfef95601890afd80709
Digest validation failed for stderr.log, expecting 0xda39a3ee5e6b4b0d3255bfef95601890afd80709 found 0x3c11277a27db939d6885f6da70bfcf741bd4414d
===== DaCapo evaluation-git-69a704e zxing FAILED warmup =====
===== DaCapo evaluation-git-69a704e zxing starting warmup 4 =====
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff5f00f4c6e, pid=17108, tid=17264
#
# JRE version: OpenJDK Runtime Environment (11.0.11) (build 11.0.11-internal+0-adhoc.xinyuz.openjdk)
# Java VM: OpenJDK 64-Bit Server VM (11.0.11-internal+0-adhoc.xinyuz.openjdk, compiled mode, third-party gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x480c6e]  BiasedLocking::revoke_and_rebias(Handle, bool, Thread*)+0x1e
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/xinyuz/core.17108)
#
# An error report file with more information is saved as:
# /home/xinyuz/hs_err_pid17108.log
[thread 17260 also had an error][thread 17268 also had an error][thread 17249 also had an error][thread 17263 also had an error][thread 17266 also had an error][thread 17265 also had an error][thread 17245 also had an error][thread 17258 also had an error][thread 17246 also had an error][thread 17251 also had an error][thread 17262 also had an error][thread 17261 also had an error][thread 17248 also had an error]
[thread 17255 also had an error]












#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by caizixian** [comment]
I can't reproduce the exact problem but did observe a crash. 

Core revision: dbf03163

OpenJDK binding revision: https://github.com/mmtk/mmtk-openjdk/commit/648bb27f4bb5c84a83f74fda1d699514548cf663

```
MMTK_PLAN=SemiSpace ./core-dbf03163-openjdk-648bb27f/jdk/bin/java -XX:MetaspaceSize=500M -XX:+DisableExplicitGC -server -XX:-TieredCompilation -Xcomp -XX:+UseThirdPartyHeap -Djava.library.path=/home/zixianc/MMTk-Dev/evaluation/probes -Dprobes=RustMMTk -Xms576M -Xmx576M -cp /usr/share/benchmarks/dacapo/dacapo-evaluation-git-69a704e.jar:/home/zixianc/MMTk-Dev/evaluation/probes:/home/zixianc/MMTk-Dev/evaluation/probes/probes.jar Harness -c probe.DacapoChopinCallback -n 5 zxing

--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 24 processors detected, 24 threads used to drive the workload, in a possible range of [1,unlimited]
===== DaCapo evaluation-git-69a704e zxing starting warmup 1 =====

Decoded 945 files out of 1225 successfully (77%)

Digest validation failed for stdout.log, expecting 0x5ba0fbb5c278f7344ad9c9d153a323f6b6eda10c found 0x61868d14dec37ee787d3939148352808f0d561f0
===== DaCapo evaluation-git-69a704e zxing FAILED warmup =====
===== DaCapo evaluation-git-69a704e zxing starting warmup 2 =====

Decoded 935 files out of 1225 successfully (76%)

Digest validation failed for stdout.log, expecting 0x5ba0fbb5c278f7344ad9c9d153a323f6b6eda10c found 0x2385bcacc99d7c2150e927c06295faabcb7b7053
===== DaCapo evaluation-git-69a704e zxing FAILED warmup =====
===== DaCapo evaluation-git-69a704e zxing starting warmup 3 =====

Decoded 929 files out of 1225 successfully (75%)

Digest validation failed for stdout.log, expecting 0x5ba0fbb5c278f7344ad9c9d153a323f6b6eda10c found 0x4aa69f13044f05c68f146a15d2bb08c5db4d8c81
===== DaCapo evaluation-git-69a704e zxing FAILED warmup =====
===== DaCapo evaluation-git-69a704e zxing starting warmup 4 =====

Decoded 927 files out of 1225 successfully (75%)

Digest validation failed for stdout.log, expecting 0x5ba0fbb5c278f7344ad9c9d153a323f6b6eda10c found 0x6633c74f24d9062663064f67646579f6a9c50673
===== DaCapo evaluation-git-69a704e zxing FAILED warmup =====
===== DaCapo evaluation-git-69a704e zxing starting =====
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f69672b89f6, pid=6086, tid=6108
#
# JRE version: OpenJDK Runtime Environment (11.0.11) (build 11.0.11-internal+0-adhoc.zixianc.openjdk)
# Java VM: OpenJDK 64-Bit Server VM (11.0.11-internal+0-adhoc.zixianc.openjdk, compiled mode, third-party gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xbe99f6]  mmtk_get_object_size(void*)+0x16
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/zixianc/MMTk-Dev/evaluation/build/core.6086)
#
# An error report file with more information is saved as:
# /home/zixianc/MMTk-Dev/evaluation/build/hs_err_pid6086.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
```
